In [34]:
import numpy as np
matrix = np.arange(30)
matrix = matrix.reshape(6,5)
matrix[3,4] = 0

In [6]:
# using separete data structure
zeroLocation = []
for i in range(6):
    for j in range(5):
        if matrix[i,j] == 0:
            zeroLocation.append((i,j))
for item in zeroLocation:
    iLoc,jLoc = item
    for i in range(6):
        matrix[i,jLoc] = 0
    for j in range(5):
        matrix[iLoc,j] = 0

In [35]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18,  0],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
# using No additional Data Structure we use rowHasZero and colHasZero variables
# and use that space to store the boolean values of the whole rows and columns
# then later we make them zero
rowHasZero = 0
colHasZero = 0
flag = 0 
# represents that we have not yet found the zero in the matrix

for i in range(6):
    for j in range(5):
        if matrix[i,j] == 0:
            if flag == 0:
                flag = 1
                rowHasZero = i
                colHasZero = j
            matrix[rowHasZero, j] = 0
            matrix[i, colHasZero] = 0

# make rows 0 so iterating through column
for i in range(6):
    if i != rowHasZero and matrix[i,colHasZero] == 0:
        for j in range(5):
            matrix[i,j] = 0

# make columns 0 so iterating through row
for i in range(5):
    if i != colHasZero and matrix[rowHasZero, i] == 0:
        for j in range(6):
            matrix[j,i] = 0

# making the rowHasZero row and colHasZero column as zero
for i in range(6):
    matrix[i,colHasZero] = 0
for i in range(5):
    matrix[rowHasZero,i] = 0

In [37]:
matrix

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  7,  8,  0],
       [ 0, 11, 12, 13,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 21, 22, 23,  0],
       [ 0, 26, 27, 28,  0]])

In [33]:
matrix

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  7,  8,  0],
       [ 0, 11, 12, 13,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 21, 22, 23,  0],
       [ 0, 26, 27, 28,  0]])